<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Version>1.0.0</Version>
    <Company>MistralAI</Company>
    <Authors>MistralAI</Authors>
    <Description>Mistral AI .NET Client Library for Chat Completion API</Description>
    <PackageId>MistralAI.Client</PackageId>
    <PackageTags>mistral;ai;chat;completion;api;client</PackageTags>
    <UserSecretsId>16bd4d44-20da-4929-962c-2a6f7486b7d0</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.0" />
    <PackageReference Include="Polly" Version="7.2.3" />
    <PackageReference Include="System.Net.Http.Json" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\Shared\" />
    <Folder Include="DTOs\Buffered\" />
    <Folder Include="DTOs\Streaming\" />
  </ItemGroup>

</Project>
